### ISSUE TITLE
mupdf-gl not built

### ISSUE THREAD

**Issue by ousia** [mjg/mupdf.spec#2]
@mjg, many thanks for the updated build that I directly downloaded from <https://copr-be.cloud.fedoraproject.org/results/mjg/mupdf/fedora-25-i386/>.

After installing it, I see that mupdf-gl isn’t built. Do your local builds include mupdf-gl?

**Comment by mjg** [comment]
A, GL, I remember...

I set up a second copr repo now, [mjg/mupdf-GL](https://copr.fedorainfracloud.org/coprs/mjg/mupdf-GL/) contains builds with the Open-GL app enabled (in addition to the ordinary one).

**Comment by ousia** [comment]
Many thanks for the new repo, @mjg.

Would it be possible that `mupdf` links to `mupdf-gl`, instead of `mupdf-x11`?

After all, this is mupdf-GL repo 😄.

**Comment by mjg** [comment]
mupdf-gl is now part of the stock fedora builds (has been for a while). Due to incompatibilty (keys, options), it's not a direct drop in replacement, though, so please set up any symlinks yourself.
I'll look into using "alternatives", but have to make sure no other mupdf users (packages) are affected.
