### ISSUE TITLE
icon not working in application

### ISSUE THREAD

**Issue by ousia** [mjg/mupdf.spec#3]
@mjg, here you have an image of both mupdf and xpdf displaying a file:

![icon-mupdf](https://cloud.githubusercontent.com/assets/203767/24829739/e013e680-1c77-11e7-9184-fa918870b143.png)

In both cases, titlebar doesn’t contain the application icon. But xpdf has the icon in the panel.

Would it be possible to fix at least the issue with the panel?

**Comment by mjg** [comment]
Fixed on master and in rawhide.

**Comment by ousia** [comment]
@mjg, I have just realized that `mupdf-x11` has the icon, but I’m afraid that `mupdf-gl` doesn’t have it.

![mupdf-gl-noicon](https://user-images.githubusercontent.com/203767/46143731-2f872a80-c25b-11e8-9733-a2eb0249783d.png)

**Comment by mjg** [comment]
Does mupdf-x11 have the icon when you call it as "mupdf-x11" (not as "mupdf")?

**Comment by ousia** [comment]
Yes, it has it.

**Comment by ousia** [comment]
I’m afraid that `mupdf-gl` still lacks the icon, although I read:

* Mon Oct 01 2018 Michael J Gruber <***@***.***> - 1.14rc1-3
    - mupdf-gl desktop entry

**Comment by mjg** [comment]
Well, depends on which "the icon".

The desktop entry makes mupdf-gl appear in the menu (since it has an open dialog, as opposed to mupdf-x11); this is the important functional change. Also, it specifies an icon that desktop environments use in an app list, for iconified apps and such. All of this should work with mupdf-gl now.

The icon in the title bar is different: it's an x11 window decoration that - afaik - the app itself needs to set. From all that I can tell, mupdf-gl fails to set the icon through the glut library. (mupdf-x11 sets it directly using the x11-call.)
